<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb3afd6ad87b0b437edf6814dc16d9260
{
    public static $prefixLengthsPsr4 = array (
        'V' => 
        array (
            'Valitron\\' => 9,
        ),
        'L' => 
        array (
            'Laminas\\Stdlib\\' => 15,
            'Laminas\\Db\\' => 11,
        ),
        'J' => 
        array (
            'Johnny\\TestProject\\' => 19,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Valitron\\' => 
        array (
            0 => __DIR__ . '/..' . '/vlucas/valitron/src/Valitron',
        ),
        'Laminas\\Stdlib\\' => 
        array (
            0 => __DIR__ . '/..' . '/laminas/laminas-stdlib/src',
        ),
        'Laminas\\Db\\' => 
        array (
            0 => __DIR__ . '/..' . '/laminas/laminas-db/src',
        ),
        'Johnny\\TestProject\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'U' => 
        array (
            'Upload' => 
            array (
                0 => __DIR__ . '/..' . '/scoumbourdis/upload/src',
            ),
        ),
        'P' => 
        array (
            'PHPExcel' => 
            array (
                0 => __DIR__ . '/..' . '/scoumbourdis/phpexcel/Classes',
            ),
        ),
        'G' => 
        array (
            'GroceryCrud' => 
            array (
                0 => __DIR__ . '/..' . '/grocerycrud/enterprise/src',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb3afd6ad87b0b437edf6814dc16d9260::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb3afd6ad87b0b437edf6814dc16d9260::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitb3afd6ad87b0b437edf6814dc16d9260::$prefixesPsr0;
            $loader->classMap = ComposerStaticInitb3afd6ad87b0b437edf6814dc16d9260::$classMap;

        }, null, ClassLoader::class);
    }
}
